version: "3.8"

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
    kong-database:
      image: postgres:9.6
      environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_DB=kong
        - POSTGRES_PASSWORD=postgres
      networks:
        - kong-net
      ports:
        - 5432:5432

    kong-migrations:
      depends_on:
        - kong-database
      image: kong-api-gateway
      environment: 
        - KONG_DATABASE=postgres
        - KONG_PG_HOST=kong-database
        - KONG_PG_USER=postgres
        - KONG_PG_PASSWORD=postgres
      networks:
        - kong-net
      command: sh -c "kong migrations bootstrap"
    
    kong-gateway:
      depends_on:
        - kong-database
      image: kong-api-gateway
      environment: 
        - KONG_DATABASE=postgres
        - KONG_PG_HOST=kong-database
        - KONG_PG_USER=postgres
        - KONG_PG_PASSWORD=postgres
      networks:
        - kong-net
      ports:
        - 8000:8000
        - 8443:8443
        - 8001:8001
        - 8444:8444

    backend:
      depends_on:
        - kong-database
      image: node-app
      networks:
        - kong-net
      ports:
        - 4000:4000
